### ISSUE TITLE
Insecure Local Storage of GitHub Token

### ISSUE THREAD

**Issue by tankeehock** [osmoscraft/tundra#5]
The extension uses local storage API to store sensitive credentials locally on the user's machine. However, the token is stored as plaintext in LevelDB file (.ldb). The token can be easily extracted using Linux CLI utilities such as "strings" and "grep". A recommendation approach is to adopt GitHub's OAuth integration to authorize the interaction with GitHub. This will reduce the need to store the token permanently.

**Comment by chuanqisun** [comment]
Thanks @tankeehock for pointing this out. Today I learned about the LevelDB backend that local storage is using! The use of local storage was intentional but the lack of encryption was problematic as you pointed out. I didn't want to register an OAuth app because I want to avoid handling any user private data. I wonder if there are local-first solutions to the problem. I'm curious how password managers like 1password handle it.

**Comment by chuanqisun** [comment]
In the meanwhile, I'd recommend using GitHub's Fine-grained token to reduce the risk in case of a breach. The fine-grained token should be scoped to have content read/write access on the repository that is storing the tundra notes.
